import React, { useState } from 'react';
import './Modal.css';

const Modal: React.FC = () => {
	const [isOpen, setIsOpen] = useState(true);

	const handleClose = () => {
		setIsOpen(false);
	};

	const handleBackdropClick = (event: React.MouseEvent<HTMLDivElement>) => {
		if (event.target === event.currentTarget) {
			handleClose();
		}
	};

	return (
		<>
			{isOpen && (
				<div className="backdrop" onClick={handleBackdropClick}>
					<div className="modal">
						<div className="modal-content">
							<button className="close-button" onClick={handleClose}>
								X
							</button>
							<h2>This is a <u>demonstration</u> version of our system in which the drone follows a predefined path.</h2>
							<p>
								In the final version, <b>the pilot will control the drone</b> along a path generated by the system, based on the chosen destination.<br/>
								To start the simulation, press the button <b>"start"</b> below.<br/>
								If you haven't done so yet, we encourage you to watch our presentation video.
							</p>
						</div>
					</div>
				</div>
			)}
		</>
	);
};

export default Modal;